# The source lists for PracticeTakes and PracticeTakesTests.
#
# They live here rather than in the root CMakeLists.txt because they are two
# thirds of its length and none of it is logic: 219 bare paths that every
# branch adding a file has to touch. Keeping them apart leaves the root file as
# the project's build *decisions* -- options, dependencies, targets, install
# rules -- which is the part worth reading.
#
# `include()` does not change CMAKE_CURRENT_SOURCE_DIR, so every path here is
# relative to the repository root exactly as it was before the move. Do not
# make them relative to this file.
#
# Two things outside CMake read these lists, and both find them by path:
#
#  - `.gitattributes` points the cmake-sources merge driver at this file, so
#    two branches adding a file union instead of conflicting. The driver works
#    on any file whose conflicts are entirely bare source paths -- see
#    docs/development/operations/MERGING.md.
#  - tools/scripts/quality/coverage_sources.py reads
#    PRACTICE_TAKES_TEST_SOURCES to decide what the coverage report should
#    cover. A source absent from that list is simply not in the report.
#
# Keep the lists grouped by directory, as they already are.

set(PRACTICE_TAKES_SOURCES
    src/bootstrap/main.cpp
    src/application/configuration/AppDefaults.h
    src/application/configuration/SettingsPersistence.cpp
    src/application/configuration/SettingsPersistence.h
    src/application/configuration/SettingsImportPersistence.h
    src/application/configuration/SettingsImportTransaction.h
    src/application/configuration/SettingsTransferCodec.cpp
    src/application/configuration/SettingsTransferCodec.h
    src/application/configuration/SettingsTransferFile.h
    src/application/shell/MainComponent.h
    src/application/shell/MainComponentLifecycle.cpp
    src/application/shell/WorkspaceStartupSequence.h
    src/application/shell/state/appearance/MainComponentAppearance.cpp
    src/application/shell/state/audio/MainComponentAudioState.cpp
    src/application/shell/state/testcontrol/MainComponentTestControl.cpp
    src/application/shell/ui/main_window/MainTitleBar.h
    src/application/shell/ui/main_window/MicrophoneWarning.h
    src/application/shell/ui/feedback/FeedbackWindow.h
    src/application/shell/ui/feedback/MainComponentFeedback.cpp
    src/application/shell/ui/score/MainComponentScore.cpp
    src/application/shell/ui/score/ScoreImportJob.cpp
    src/application/shell/ui/score/ScoreImportJob.h
    src/application/shell/ui/score/ScoreImportState.h
    src/application/shell/ui/score/ScoreImportSummary.cpp
    src/application/shell/ui/score/ScoreImportSummary.h
    src/application/shell/ui/score/ScoreImportWindow.h
    src/application/shell/ui/settings/MainComponentSettings.cpp
    src/application/shell/ui/settings/SettingsWindow.h
    src/application/shell/ui/workspace/components/DockedToolPanel.h
    src/application/shell/ui/workspace/components/ToolDragHandle.h
    src/application/shell/ui/workspace/components/ToolOptionsButton.h
    src/application/shell/ui/workspace/components/ToolWindow.h
    src/application/shell/ui/workspace/components/WorkspaceSplitPane.h
    src/application/shell/ui/workspace/components/WorkspaceTabBarButton.h
    src/application/shell/ui/workspace/components/WorkspaceTabbedComponent.h
    src/application/shell/ui/workspace/model/WorkspaceBuiltIns.h
    src/application/shell/ui/workspace/model/WorkspaceCatalogCodec.cpp
    src/application/shell/ui/workspace/model/WorkspaceCatalogCodec.h
    src/application/shell/ui/workspace/model/WorkspaceDocuments.h
    src/application/shell/ui/workspace/model/WorkspaceLayoutState.h
    src/application/shell/ui/workspace/model/WorkspaceMenuModel.h
    src/application/shell/ui/workspace/model/NamedWorkspaceService.h
    src/application/shell/ui/workspace/model/WorkspaceNormalizer.h
    src/application/shell/ui/workspace/model/WorkspaceSnapshotApply.h
    src/application/shell/ui/workspace/model/WorkspaceSnapshotCapture.h
    src/application/shell/ui/workspace/model/WorkspaceSessionLifecycle.h
    src/application/shell/ui/workspace/model/WorkspaceToolState.h
    src/application/shell/ui/workspace/shell/MainComponentWorkspaceDrag.cpp
    src/application/shell/ui/workspace/shell/MainComponentWorkspaceLayout.cpp
    src/application/shell/ui/workspace/shell/MainComponentWorkspaceMenu.cpp
    src/application/shell/ui/workspace/shell/MainComponentWorkspaceManagement.cpp
    src/application/shell/ui/workspace/shell/MainComponentWorkspacePresentation.cpp
    src/application/shell/ui/workspace/shell/MainComponentWorkspaceSnapshot.cpp
    src/application/testcontrol/ApprovedWindowStates.cpp
    src/application/testcontrol/ApprovedWindowStates.h
    src/application/testcontrol/TestControlChannel.cpp
    src/application/testcontrol/TestControlChannel.h
    src/application/testcontrol/TestControlClicker.cpp
    src/application/testcontrol/TestControlClicker.h
    src/application/testcontrol/TestControlCommand.cpp
    src/application/testcontrol/TestControlCommand.h
    src/application/testcontrol/TestControlSession.cpp
    src/application/testcontrol/TestControlSession.h
    src/application/testcontrol/TestControlTarget.h
    src/application/theme/AppLookAndFeel.cpp
    src/application/theme/Theme.cpp
    src/application/theme/Theme.h
    src/application/theme/ThemeType.h
    src/application/tools/BuiltInToolCatalog.h
    src/application/tools/BuiltInTools.cpp
    src/application/tools/BuiltInTools.h
    src/application/tools/ToolCatalog.h
    src/application/tools/ToolComponent.h
    src/application/tools/ToolInstanceAllocator.h
    src/application/tools/ToolInstanceId.h
    src/application/tools/ToolRegistry.h
    src/application/tools/ToolServices.h
    src/application/tools/ToolSettingsPayload.h
    src/features/analysis/spectrogram/SpectrogramComponent.cpp
    src/features/analysis/spectrogram/SpectrogramComponent.h
    src/features/analysis/harmonics/HarmonicAnalyzer.cpp
    src/features/analysis/harmonics/HarmonicAnalyzer.h
    src/features/analysis/harmonics/HarmonicAnalyzerComponent.cpp
    src/features/analysis/harmonics/HarmonicAnalyzerComponent.h
    src/features/analysis/tuner/PitchTracker.cpp
    src/features/analysis/tuner/PitchTracker.h
    src/features/analysis/tuner/TunerComponent.cpp
    src/features/analysis/tuner/TunerComponent.h
    src/features/analysis/tuner/TunerSettingsCodec.cpp
    src/features/analysis/tuner/TunerSettingsCodec.h
    src/features/analysis/tuner/TunerDrawing.cpp
    src/features/performance/ApplicationLaunchTimer.cpp
    src/features/performance/ApplicationLaunchTimer.h
    src/features/feedback/FeedbackComponent.cpp
    src/features/feedback/FeedbackComponent.h
    src/features/feedback/FeedbackInvitationPolicy.h
    src/platform/audio/AudioInputService.cpp
    src/platform/audio/AudioInputService.h
    src/platform/audio/AudioRecoveryPolicy.h
    src/platform/audio/AudioSampleFifo.h
    src/platform/audio/PitchDetector.cpp
    src/platform/audio/PitchDetector.h
    src/platform/audio/SharedPitchAnalysis.cpp
    src/platform/audio/SharedPitchAnalysis.h
    src/platform/audio/SyntheticTone.h
    src/platform/score/Diagnostic.h
    src/platform/score/LyricSyllable.h
    src/platform/score/Measure.h
    src/platform/score/MusicalTime.h
    src/platform/score/Pitch.h
    src/platform/score/Score.h
    src/platform/score/ScoreAttributes.h
    src/platform/score/ScoreBuilder.cpp
    src/platform/score/ScoreBuilder.h
    src/platform/score/ScoreEvent.h
    src/platform/score/ScoreInvariants.cpp
    src/platform/score/ScoreInvariants.h
    src/platform/score/TempoMap.cpp
    src/platform/score/TempoMap.h
    src/platform/score/musicxml/MusicXmlDiagnosticSink.cpp
    src/platform/score/musicxml/MusicXmlDiagnosticSink.h
    src/platform/score/musicxml/MusicXmlImportResult.h
    src/platform/score/musicxml/MusicXmlImporter.cpp
    src/platform/score/musicxml/MusicXmlImporter.h
    src/platform/score/musicxml/XmlDocumentAdapter.cpp
    src/platform/score/musicxml/XmlDocumentAdapter.h
    src/platform/score/musicxml/container/MusicXmlContainer.cpp
    src/platform/score/musicxml/container/MusicXmlContainer.h
    src/platform/score/musicxml/read/MusicXmlMeasureReader.cpp
    src/platform/score/musicxml/read/MusicXmlMeasureReader.h
    src/platform/score/musicxml/read/MusicXmlReadContext.cpp
    src/platform/score/musicxml/read/MusicXmlReadContext.h
    src/platform/score/musicxml/read/MusicXmlScoreReader.cpp
    src/platform/score/musicxml/read/MusicXmlScoreReader.h
    src/platform/score/musicxml/read/MusicXmlSubset.cpp
    src/platform/score/musicxml/read/MusicXmlSubset.h
    src/platform/score/musicxml/read/MusicXmlTieResolver.cpp
    src/platform/score/musicxml/read/MusicXmlTieResolver.h
    src/platform/score/musicxml/read/MusicXmlValueParsing.cpp
    src/platform/score/musicxml/read/MusicXmlValueParsing.h
)
# The test target is not just the tests: it also compiles the production
# sources under test, and deliberately only those. A file added here starts
# being covered; a file left out is invisible to both the suite and the
# coverage report.
set(PRACTICE_TAKES_TEST_SOURCES
    src/platform/audio/AudioInputService.cpp
    src/platform/audio/AudioInputService.h
    src/tests/application/configuration/AppDefaultsTests.cpp
    src/tests/application/configuration/SettingsPersistenceTests.cpp
    src/tests/application/configuration/SettingsTransferCodecTests.cpp
    src/tests/application/shell/WorkspaceStartupSequenceTests.cpp
    src/tests/application/shell/ui/score/ScoreImportStateTests.cpp
    src/tests/application/shell/ui/score/ScoreImportSummaryTests.cpp
    src/tests/application/shell/ui/workspace/components/WorkspacePresentationComponentsTests.cpp
    src/tests/application/shell/ui/workspace/model/NamedWorkspaceServiceTests.cpp
    src/tests/application/shell/ui/workspace/model/WorkspaceBuiltInsTests.cpp
    src/tests/application/shell/ui/workspace/model/WorkspaceCatalogCodecTests.cpp
    src/tests/application/shell/ui/workspace/model/WorkspaceDocumentsTests.cpp
    src/tests/application/shell/ui/workspace/model/WorkspaceLayoutStateTests.cpp
    src/tests/application/shell/ui/workspace/model/WorkspaceMenuModelTests.cpp
    src/tests/application/shell/ui/workspace/model/WorkspaceRecoveryTests.cpp
    src/tests/application/shell/ui/workspace/model/WorkspaceSessionLifecycleTests.cpp
    src/tests/application/shell/ui/workspace/model/WorkspaceSnapshotApplyTests.cpp
    src/tests/application/shell/ui/workspace/model/WorkspaceSnapshotCaptureTests.cpp
    src/tests/application/shell/ui/workspace/model/WorkspaceToolStateTests.cpp
    src/tests/application/testcontrol/ApprovedWindowStatesTests.cpp
    src/tests/application/theme/AppLookAndFeelTests.cpp
    src/tests/application/tools/CompactPresentationTests.cpp
    src/tests/application/tools/ToolCatalogTests.cpp
    src/tests/application/tools/ToolLifecycleTests.cpp
    src/tests/application/tools/UnknownToolIntegrationTests.cpp
    src/tests/application/tools/ToolInstanceIdTests.cpp
    src/tests/application/testcontrol/TestControlClickerTests.cpp
    src/tests/application/testcontrol/TestControlCommandTests.cpp
    src/tests/application/testcontrol/TestControlSessionTests.cpp
    src/tests/application/theme/ThemeContrastTests.cpp
    src/tests/features/analysis/harmonics/HarmonicAnalyzerTests.cpp
    src/tests/features/analysis/tuner/PitchTrackerTests.cpp
    src/tests/features/feedback/FeedbackInvitationPolicyTests.cpp
    src/tests/features/performance/ApplicationLaunchTimerTests.cpp
    src/tests/platform/audio/AudioRecoveryPolicyTests.cpp
    src/tests/platform/audio/AudioInputServiceTests.cpp
    src/tests/platform/audio/AudioSampleFifoLoadTests.cpp
    src/tests/platform/audio/AudioSampleFifoTests.cpp
    src/tests/platform/audio/SyntheticToneTests.cpp
    src/tests/platform/audio/PitchDetectorTests.cpp
    src/tests/platform/audio/SharedPitchAnalysisTests.cpp
    src/tests/platform/score/MusicalTimeTests.cpp
    src/tests/platform/score/PitchTests.cpp
    src/tests/platform/score/ScoreInvariantsTests.cpp
    src/tests/platform/score/ScoreModelTests.cpp
    src/tests/platform/score/TempoMapTests.cpp
    src/tests/platform/score/musicxml/MusicXmlCorpusTests.cpp
    src/tests/platform/score/musicxml/container/MusicXmlContainerTests.cpp
    src/tests/platform/score/musicxml/read/MusicXmlAttributeTests.cpp
    src/tests/platform/score/musicxml/read/MusicXmlDiagnosticsTests.cpp
    src/tests/platform/score/musicxml/read/MusicXmlLyricTests.cpp
    src/tests/platform/score/musicxml/read/MusicXmlNoteTests.cpp
    src/tests/platform/score/musicxml/read/MusicXmlPercussionTests.cpp
    src/tests/platform/score/musicxml/read/MusicXmlTimingTests.cpp
    src/tests/platform/score/musicxml/read/MusicXmlTranspositionTests.cpp
    src/application/configuration/SettingsPersistence.cpp
    src/application/configuration/SettingsTransferCodec.cpp
    src/features/analysis/tuner/TunerSettingsCodec.cpp
    src/application/shell/ui/score/ScoreImportSummary.cpp
    src/application/shell/ui/workspace/model/WorkspaceCatalogCodec.cpp
    src/application/testcontrol/ApprovedWindowStates.cpp
    src/application/testcontrol/TestControlClicker.cpp
    src/application/testcontrol/TestControlCommand.cpp
    src/application/testcontrol/TestControlSession.cpp
    src/application/theme/AppLookAndFeel.cpp
    src/application/theme/Theme.cpp
    src/features/analysis/harmonics/HarmonicAnalyzer.cpp
    src/features/analysis/tuner/PitchTracker.cpp
    src/features/performance/ApplicationLaunchTimer.cpp
    src/platform/audio/PitchDetector.cpp
    src/platform/audio/SharedPitchAnalysis.cpp
    src/platform/score/ScoreBuilder.cpp
    src/platform/score/ScoreInvariants.cpp
    src/platform/score/TempoMap.cpp
    src/platform/score/musicxml/MusicXmlDiagnosticSink.cpp
    src/platform/score/musicxml/MusicXmlImporter.cpp
    src/platform/score/musicxml/XmlDocumentAdapter.cpp
    src/platform/score/musicxml/container/MusicXmlContainer.cpp
    src/platform/score/musicxml/read/MusicXmlMeasureReader.cpp
    src/platform/score/musicxml/read/MusicXmlReadContext.cpp
    src/platform/score/musicxml/read/MusicXmlScoreReader.cpp
    src/platform/score/musicxml/read/MusicXmlSubset.cpp
    src/platform/score/musicxml/read/MusicXmlTieResolver.cpp
    src/platform/score/musicxml/read/MusicXmlValueParsing.cpp
)
