#include <JuceHeader.h>

#include <iostream>

#include "app/MainComponent.h"
#include "app/MainTitleBar.h"

// JUCE owns the application object for the lifetime of the process. This class
// creates the main window during startup and releases it during shutdown.
class PracticeTakesApplication final : public juce::JUCEApplication
{
  public:
    [[nodiscard]] const juce::String getApplicationName() override
    {
        return "Practice Takes";
    }

    [[nodiscard]] const juce::String getApplicationVersion() override
    {
        // ProjectInfo is generated by JUCE from the root VERSION file through
        // CMake, so the visible application version has one source of truth.
        return ProjectInfo::versionString;
    }

    [[nodiscard]] bool moreThanOneInstanceAllowed() override
    {
        // Separate instances are useful while testing multiple audio devices
        // or comparing different builds.
        return true;
    }

    void initialise(const juce::String& commandLineArguments) override
    {
        const auto argument = commandLineArguments.trim();

        if (argument == "-v" || argument == "--version")
        {
            std::cout << getApplicationName() << " v" << getApplicationVersion() << '\n';
            quit();
            return;
        }

        const auto windowTitle = getApplicationName() + " v" + getApplicationVersion();

        mainWindow = std::make_unique<MainWindow>(windowTitle);
    }

    void shutdown() override
    {
        // Destroy the window before JUCE tears down its GUI infrastructure.
        mainWindow.reset();
    }

    void systemRequestedQuit() override
    {
        quit();
    }

  private:
    // The top-level window owns MainComponent and therefore all shared audio,
    // settings, warning, and tool-window state.
    class MainWindow final : public juce::DocumentWindow
    {
      public:
        explicit MainWindow(const juce::String& title)
            : DocumentWindow(title, juce::Colour::fromRGB(18, 20, 27),
                             juce::DocumentWindow::allButtons)
        {
            setUsingNativeTitleBar(false);

            auto* content = new MainComponent();
            setContentOwned(content, true);

            auto customTitleBar = content->createTitleBar(
                title, [this] { setMinimised(true); }, [this] { toggleFullscreen(); },
                [this] { closeButtonPressed(); });
            setTitleBarHeight(42);
            setTitleBarButtonsRequired(0, false);
            titleBar = std::move(customTitleBar);
            juce::Component::addAndMakeVisible(titleBar.get());
            // Use a resizable border so every window edge and corner can be
            // dragged, even though the application supplies its own title bar.
            setResizable(true, false);
            centreWithSize(getWidth(), getHeight());
            setVisible(true);
        }

        void closeButtonPressed() override
        {
            juce::JUCEApplication::getInstance()->systemRequestedQuit();
        }

        void resized() override
        {
            DocumentWindow::resized();
            if (titleBar != nullptr)
            {
                titleBar->setBounds(0, 0, getWidth(), getTitleBarHeight());
                titleBar->toFront(false);
            }
        }

        bool keyPressed(const juce::KeyPress& key) override
        {
            if (key.getKeyCode() == juce::KeyPress::F11Key)
            {
                toggleFullscreen();
                return true;
            }

            if (key == juce::KeyPress::escapeKey && isFullScreen())
            {
                setFullscreen(false);
                return true;
            }

            return DocumentWindow::keyPressed(key);
        }

      private:
        void toggleFullscreen()
        {
            setFullscreen(!isFullScreen());
        }

        void setFullscreen(bool shouldBeFullscreen)
        {
            setFullScreen(shouldBeFullscreen);
            if (!shouldBeFullscreen)
            {
                setResizable(true, false);
            }

            if (titleBar != nullptr)
            {
                titleBar->setFullscreen(shouldBeFullscreen);
            }
        }

        std::unique_ptr<MainTitleBar> titleBar;
    };

    std::unique_ptr<MainWindow> mainWindow;
};

START_JUCE_APPLICATION(PracticeTakesApplication)
