#if defined(__linux__)
#include <X11/Xatom.h>
#include <X11/Xlib.h>
#undef KeyPress
#undef None
#endif

#include <JuceHeader.h>

#include <cstdint>
#include <iostream>

#include "../application/shell/MainComponent.h"
#include "../application/shell/ui/main_window/MainTitleBar.h"

namespace
{
void setOperatingSystemFullscreen(juce::Component& component, bool shouldBeFullscreen)
{
#if JUCE_LINUX
    auto* display = XOpenDisplay(nullptr);
    if (display == nullptr || component.getWindowHandle() == nullptr)
    {
        if (display != nullptr)
            XCloseDisplay(display);
        return;
    }

    const auto window =
        static_cast<::Window>(reinterpret_cast<std::uintptr_t>(component.getWindowHandle()));
    XEvent event{};
    event.xclient.type = ClientMessage;
    event.xclient.window = window;
    event.xclient.message_type = XInternAtom(display, "_NET_WM_STATE", False);
    event.xclient.format = 32;
    event.xclient.data.l[0] = shouldBeFullscreen ? 1 : 0;
    event.xclient.data.l[1] =
        static_cast<long>(XInternAtom(display, "_NET_WM_STATE_FULLSCREEN", False));
    event.xclient.data.l[3] = 1;

    XSendEvent(
        display, DefaultRootWindow(display), False,
        SubstructureRedirectMask | SubstructureNotifyMask, &event);
    XCloseDisplay(display);
#else
    juce::ignoreUnused(component, shouldBeFullscreen);
#endif
}
} // namespace

// JUCE owns the application object for the lifetime of the process. This class
// creates the main window during startup and releases it during shutdown.
class PracticeTakesApplication final : public juce::JUCEApplication
{
  public:
    [[nodiscard]] const juce::String getApplicationName() override
    {
        return "Practice Takes";
    }

    [[nodiscard]] const juce::String getApplicationVersion() override
    {
        // ProjectInfo is generated by JUCE from the root VERSION file through
        // CMake, so the visible application version has one source of truth.
        return ProjectInfo::versionString;
    }

    [[nodiscard]] bool moreThanOneInstanceAllowed() override
    {
        // Separate instances are useful while testing multiple audio devices
        // or comparing different builds.
        return true;
    }

    void initialise(const juce::String& commandLineArguments) override
    {
        const auto argument = commandLineArguments.trim();

        if (argument == "-v" || argument == "--version")
        {
            std::cout << getApplicationName() << " v" << getApplicationVersion() << '\n';
            quit();
            return;
        }

        const auto windowTitle = getApplicationName() + " v" + getApplicationVersion();

        mainWindow = std::make_unique<MainWindow>(windowTitle);
    }

    void shutdown() override
    {
        // Destroy the window before JUCE tears down its GUI infrastructure.
        mainWindow.reset();
    }

    void systemRequestedQuit() override
    {
        quit();
    }

  private:
    // The top-level window owns MainComponent and therefore all shared audio,
    // settings, warning, and tool-window state.
    class MainWindow final : public juce::DocumentWindow, private juce::Timer
    {
      public:
        explicit MainWindow(const juce::String& title)
            : DocumentWindow(
                  title,
                  juce::Colour::fromRGB(18, 20, 27),
                  juce::DocumentWindow::allButtons)
        {
            setUsingNativeTitleBar(false);

            content = new MainComponent();
            setContentOwned(content, true);

            auto customTitleBar = content->createTitleBar(
                title, [this] { setMinimised(true); }, [this] { toggleFullscreen(); },
                [this] { closeButtonPressed(); });
            setTitleBarHeight(42);
            setTitleBarButtonsRequired(0, false);
            titleBar = std::move(customTitleBar);
            juce::Component::addAndMakeVisible(titleBar.get());
            // Use a resizable border so every window edge and corner can be
            // dragged, even though the application supplies its own title bar.
            setResizable(true, false);
            setResizeLimits(980, 600, 3200, 2200);
            centreWithSize(getWidth(), getHeight());
            setVisible(true);
        }

        ~MainWindow() override
        {
            if (fullscreenActive)
                setFullscreen(false);
        }

        void closeButtonPressed() override
        {
            juce::JUCEApplication::getInstance()->systemRequestedQuit();
        }

        void resized() override
        {
            DocumentWindow::resized();
            if (titleBar != nullptr)
            {
                titleBar->setBounds(0, 0, getWidth(), getTitleBarHeight());
                titleBar->toFront(false);
            }
        }

        bool keyPressed(const juce::KeyPress& key) override
        {
            if (key.getKeyCode() == juce::KeyPress::F11Key)
            {
                toggleFullscreen();
                return true;
            }

            if (key == juce::KeyPress::escapeKey && fullscreenActive)
            {
                setFullscreen(false);
                return true;
            }

            return DocumentWindow::keyPressed(key);
        }

      private:
        void toggleFullscreen()
        {
            setFullscreen(!fullscreenActive);
        }

        void setFullscreen(bool shouldBeFullscreen)
        {
            auto& desktop = juce::Desktop::getInstance();

            if (shouldBeFullscreen)
            {
                activeFullscreenMode = content != nullptr ? content->fullscreenMode()
                                                          : AppSettings::FullscreenMode::normal;
                fullscreenActive = true;

                if (activeFullscreenMode == AppSettings::FullscreenMode::kiosk)
                {
                    desktop.setKioskModeComponent(this, false);
                    startTimerHz(30);
                }
                else
                {
                    setFullScreen(true);
                }

                setOperatingSystemFullscreen(*this, true);
            }
            else
            {
                fullscreenActive = false;
                stopTimer();
                setOperatingSystemFullscreen(*this, false);

                if (activeFullscreenMode == AppSettings::FullscreenMode::kiosk)
                {
                    desktop.setKioskModeComponent(nullptr, false);
                }
                else
                {
                    setFullScreen(false);
                }

                setResizable(true, false);
            }

            if (titleBar != nullptr)
            {
                titleBar->setFullscreen(shouldBeFullscreen);
                titleBar->setVisible(
                    !shouldBeFullscreen ||
                    activeFullscreenMode == AppSettings::FullscreenMode::normal);
            }
        }

        void timerCallback() override
        {
            if (!fullscreenActive || activeFullscreenMode != AppSettings::FullscreenMode::kiosk ||
                titleBar == nullptr)
            {
                return;
            }

            const auto pointer = getMouseXYRelative();
            const auto pointerIsInside = getLocalBounds().contains(pointer);
            constexpr int revealDistance = 5;
            constexpr int hideDistanceBelowTitleBar = 10;
            const auto visibleLimit = getTitleBarHeight() + hideDistanceBelowTitleBar;
            const auto shouldShow =
                pointerIsInside &&
                (titleBar->isVisible() ? pointer.y <= visibleLimit : pointer.y <= revealDistance);
            titleBar->setVisible(shouldShow);
        }

        MainComponent* content = nullptr;
        std::unique_ptr<MainTitleBar> titleBar;
        AppSettings::FullscreenMode activeFullscreenMode = AppSettings::FullscreenMode::normal;
        bool fullscreenActive = false;
    };

    std::unique_ptr<MainWindow> mainWindow;
};

START_JUCE_APPLICATION(PracticeTakesApplication)
