#if defined(__linux__)
#include <X11/Xatom.h>
#include <X11/Xlib.h>
#undef KeyPress
#undef None
#endif

#include <JuceHeader.h>
#include <PracticeTakesIcon.h>

#if PRACTICE_TAKES_ENABLE_TEST_CONTROL
#include "../application/testcontrol/TestControlChannel.h"
#endif

#include <cstddef>
#include <cstdint>
#include <iostream>

#include "../application/shell/MainComponent.h"
#include "../application/shell/WorkspaceStartupSequence.h"
#include "../application/shell/ui/main_window/MainTitleBar.h"
#include "../features/performance/ApplicationLaunchTimer.h"

namespace
{
void setOperatingSystemFullscreen(juce::Component& component, bool shouldBeFullscreen)
{
#if JUCE_LINUX
    auto* display = XOpenDisplay(nullptr);
    if (display == nullptr || component.getWindowHandle() == nullptr)
    {
        if (display != nullptr)
        {
            XCloseDisplay(display);
        }
        return;
    }

    const auto window =
        static_cast<::Window>(reinterpret_cast<std::uintptr_t>(component.getWindowHandle()));
    XEvent event{};
    event.xclient.type = ClientMessage;
    event.xclient.window = window;
    event.xclient.message_type = XInternAtom(display, "_NET_WM_STATE", False);
    event.xclient.format = 32;
    event.xclient.data.l[0] = shouldBeFullscreen ? 1 : 0;
    event.xclient.data.l[1] =
        static_cast<long>(XInternAtom(display, "_NET_WM_STATE_FULLSCREEN", False));
    event.xclient.data.l[3] = 1;

    XSendEvent(
        display, DefaultRootWindow(display), False,
        SubstructureRedirectMask | SubstructureNotifyMask, &event);
    XCloseDisplay(display);
#else
    juce::ignoreUnused(component, shouldBeFullscreen);
#endif
}
} // namespace

// JUCE owns the application object for the lifetime of the process. This class
// creates the main window during startup and releases it during shutdown.
class PracticeTakesApplication final : public juce::JUCEApplication
{
  public:
    [[nodiscard]] const juce::String getApplicationName() override
    {
        return "Practice Takes";
    }

    [[nodiscard]] const juce::String getApplicationVersion() override
    {
        // ProjectInfo is generated by JUCE from the root VERSION file through
        // CMake, so the visible application version has one source of truth.
        return ProjectInfo::versionString;
    }

    [[nodiscard]] bool moreThanOneInstanceAllowed() override
    {
        // Separate instances are useful while testing multiple audio devices
        // or comparing different builds.
        return true;
    }

    void initialise(const juce::String& commandLineArguments) override
    {
        const auto argument = commandLineArguments.trim();

        if (argument == "-v" || argument == "--version")
        {
            std::cout << getApplicationName() << " v" << getApplicationVersion() << '\n';
            quit();
            return;
        }

        juce::StringArray arguments;
        arguments.addTokens(argument, true);
        const auto muteMicrophoneForSession = arguments.contains("--mute-microphone");
        juce::String uiValidationScenario;
        if (const auto scenarioIndex = arguments.indexOf("--ui-validation-scenario");
            scenarioIndex >= 0 && scenarioIndex + 1 < arguments.size())
        {
            uiValidationScenario = arguments[scenarioIndex + 1];
        }
        juce::String testControlState;
        if (const auto stateIndex = arguments.indexOf("--test-state");
            stateIndex >= 0 && stateIndex + 1 < arguments.size())
        {
            testControlState = arguments[stateIndex + 1];
        }
        const auto testControlChannelRequested = arguments.contains("--test-control");

#if !PRACTICE_TAKES_ENABLE_TEST_CONTROL
        if (testControlState.isNotEmpty() || testControlChannelRequested)
        {
            std::cerr << "The test control channel is disabled; rebuild with "
                         "-DPRACTICE_TAKES_ENABLE_TEST_CONTROL=ON\n";
            setApplicationReturnValue(2);
            quit();
            return;
        }
#endif

        const auto windowTitle = getApplicationName() + " v" + getApplicationVersion();

        mainWindow = std::make_unique<MainWindow>(
            windowTitle, muteMicrophoneForSession, uiValidationScenario, testControlState,
            testControlChannelRequested);
    }

    void shutdown() override
    {
        // Destroy the window before JUCE tears down its GUI infrastructure.
        mainWindow.reset();
    }

    void systemRequestedQuit() override
    {
        quit();
    }

  private:
    // The top-level window owns MainComponent and therefore all shared audio,
    // settings, warning, and tool-window state.
    class MainWindow final : public juce::DocumentWindow, private juce::Timer
    {
      public:
        MainWindow(
            const juce::String& title,
            bool muteMicrophoneForSession,
            const juce::String& uiValidationScenario,
            const juce::String& testControlState,
            bool testControlChannelRequested)
            : DocumentWindow(
                  title,
                  juce::Colour::fromRGB(18, 20, 27),
                  juce::DocumentWindow::allButtons)
        {
            setUsingNativeTitleBar(false);

            content = new MainComponent(muteMicrophoneForSession);
            setContentOwned(content, true);

            auto customTitleBar = content->createTitleBar(
                title, [this] { setMinimised(true); }, [this] { toggleFullscreen(); },
                [this] { closeButtonPressed(); });
            setTitleBarHeight(42);
            setTitleBarButtonsRequired(0, false);
            titleBar = std::move(customTitleBar);
            juce::Component::addAndMakeVisible(titleBar.get());
            // Use a resizable border so every window edge and corner can be
            // dragged, even though the application supplies its own title bar.
            setResizable(true, false);
            setResizeLimits(980, 600, 3200, 2200);
            centreWithSize(getWidth(), getHeight());
            WorkspaceStartupSequence::run(
                [this] { content->restoreLoadedWorkspace(); },
                [this]
                {
                    setVisible(true);
                    // The window has a native peer only once it is visible, and
                    // the icon reaches the window manager through that peer.
                    applyApplicationIcon();
                    performance::markMainWindowVisible();
                },
                [this] { content->initialiseAudioAfterLaunch(); });
            if (uiValidationScenario.isNotEmpty())
            {
                content->runUiValidationScenario(uiValidationScenario);
            }
#if PRACTICE_TAKES_ENABLE_TEST_CONTROL
            startTestControl(testControlState, testControlChannelRequested);
#else
            juce::ignoreUnused(testControlState, testControlChannelRequested);
#endif
        }

        ~MainWindow() override
        {
            if (fullscreenActive)
            {
                setFullscreen(false);
            }
        }

        void closeButtonPressed() override
        {
            juce::JUCEApplication::getInstance()->systemRequestedQuit();
        }

        void resized() override
        {
            DocumentWindow::resized();
            if (titleBar != nullptr)
            {
                titleBar->setBounds(0, 0, getWidth(), getTitleBarHeight());
                titleBar->toFront(false);
            }
        }

        bool keyPressed(const juce::KeyPress& key) override
        {
            if (key.getKeyCode() == juce::KeyPress::F11Key)
            {
                toggleFullscreen();
                return true;
            }

            if (key == juce::KeyPress::escapeKey && fullscreenActive)
            {
                setFullscreen(false);
                return true;
            }

            return DocumentWindow::keyPressed(key);
        }

      private:
        // Publishes the application icon to the window manager. DocumentWindow
        // only keeps its own copy for the title bar it would otherwise draw, so
        // the peer has to be told separately, and it exists only once the
        // window is visible.
        void applyApplicationIcon()
        {
            auto* peer = getPeer();
            if (peer == nullptr)
            {
                return;
            }

            const auto icon = juce::ImageFileFormat::loadFrom(
                PracticeTakesIcon::practicetakes128_png,
                static_cast<std::size_t>(PracticeTakesIcon::practicetakes128_pngSize));

            if (icon.isValid())
            {
                peer->setIcon(icon);
            }
        }

        void toggleFullscreen()
        {
            setFullscreen(!fullscreenActive);
        }

        void setFullscreen(bool shouldBeFullscreen)
        {
            auto& desktop = juce::Desktop::getInstance();

            if (shouldBeFullscreen)
            {
                activeFullscreenMode = content != nullptr ? content->fullscreenMode()
                                                          : AppSettings::FullscreenMode::normal;
                fullscreenActive = true;

                if (activeFullscreenMode == AppSettings::FullscreenMode::kiosk)
                {
                    desktop.setKioskModeComponent(this, false);
                    startTimerHz(30);
                }
                else
                {
                    setFullScreen(true);
                }

                setOperatingSystemFullscreen(*this, true);
            }
            else
            {
                fullscreenActive = false;
                stopTimer();
                setOperatingSystemFullscreen(*this, false);

                if (activeFullscreenMode == AppSettings::FullscreenMode::kiosk)
                {
                    desktop.setKioskModeComponent(nullptr, false);
                }
                else
                {
                    setFullScreen(false);
                }

                setResizable(true, false);
            }

            if (titleBar != nullptr)
            {
                titleBar->setFullscreen(shouldBeFullscreen);
                titleBar->setVisible(
                    !shouldBeFullscreen ||
                    activeFullscreenMode == AppSettings::FullscreenMode::normal);
            }
        }

        void timerCallback() override
        {
            if (!fullscreenActive || activeFullscreenMode != AppSettings::FullscreenMode::kiosk ||
                titleBar == nullptr)
            {
                return;
            }

            const auto pointer = getMouseXYRelative();
            const auto pointerIsInside = getLocalBounds().contains(pointer);
            constexpr int revealDistance = 5;
            constexpr int hideDistanceBelowTitleBar = 10;
            const auto visibleLimit = getTitleBarHeight() + hideDistanceBelowTitleBar;
            const auto shouldShow =
                pointerIsInside &&
                (titleBar->isVisible() ? pointer.y <= visibleLimit : pointer.y <= revealDistance);
            titleBar->setVisible(shouldShow);
        }

#if PRACTICE_TAKES_ENABLE_TEST_CONTROL
        // Start the application in an approved state, and optionally open the
        // control channel so the harness can drive it further.
        //
        // The state is applied after a short delay for the same reason
        // runUiValidationScenario waits: the workspace is restored
        // asynchronously after launch, and applying a state before that lands
        // would have the restore overwrite it.
        void startTestControl(const juce::String& state, bool channelRequested)
        {
            if (state.isEmpty() && !channelRequested)
            {
                return;
            }

            juce::Timer::callAfterDelay(
                500,
                [this, state, channelRequested]
                {
                    if (content == nullptr)
                    {
                        return;
                    }

                    if (state.isNotEmpty())
                    {
                        const auto* approved =
                            testcontrol::findApprovedWindowState(state.toStdString());

                        if (approved == nullptr || !content->applyTestControlState(*approved))
                        {
                            std::cerr << "Could not start in test state '" << state << "'\n";
                            juce::JUCEApplication::getInstance()->setApplicationReturnValue(3);
                            juce::JUCEApplication::getInstance()->quit();
                            return;
                        }
                    }

                    if (channelRequested)
                    {
                        openTestControlChannel();
                    }
                });
        }

        // Wiring the channel to the shell, at class scope rather than nested
        // inside startTestControl's timer callback. Five levels of indentation
        // left these lambdas straddling the column limit, which two
        // clang-format versions then disagreed about -- 21 accepted what 18
        // rejected, so CI failed on formatting that was locally clean.
        void openTestControlChannel()
        {
            testControlTarget.onApplyState = [this](const testcontrol::ApprovedWindowState& state)
            { return content != nullptr && content->applyTestControlState(state); };

            testControlTarget.onClick = [this](const std::string& id)
            { return content != nullptr && content->clickTestControlTarget(id); };

            testControlTarget.onGeometry = [this](const std::string& geometry)
            { return content != nullptr && content->applyTestControlGeometry(geometry); };

            testControlTarget.onTheme = [this](const std::string& theme)
            { return content != nullptr && content->applyTestControlTheme(theme); };

            testControlTarget.onCurrentStateId = [this]
            { return content != nullptr ? content->currentTestControlStateId() : std::string{}; };

            testControlTarget.onHasInput = [this]
            { return content != nullptr && content->hasUsableMicrophone(); };

            testControlTarget.onQuit = []
            { juce::JUCEApplication::getInstance()->systemRequestedQuit(); };

            testControlChannel =
                std::make_unique<testcontrol::TestControlChannel>(testControlTarget);
        }

        testcontrol::FunctionTestControlTarget testControlTarget;
        std::unique_ptr<testcontrol::TestControlChannel> testControlChannel;
#endif

        MainComponent* content = nullptr;
        std::unique_ptr<MainTitleBar> titleBar;
        AppSettings::FullscreenMode activeFullscreenMode = AppSettings::FullscreenMode::normal;
        bool fullscreenActive = false;
    };

    std::unique_ptr<MainWindow> mainWindow;
};

START_JUCE_APPLICATION(PracticeTakesApplication)
